#!/bin/bash
# 🚀 SCRIPT DE INICIO RÁPIDO - Sistema de Notificaciones por Email

echo "═══════════════════════════════════════════════════════════════════"
echo "  ✅ Sistema de Notificaciones por Email para RRHH"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "📋 PASOS PARA EMPEZAR:"
echo ""
echo "1️⃣  LEE LA DOCUMENTACIÓN (5 minutos)"
echo "   → Abre y lee: README_EMAIL.md"
echo ""
echo "2️⃣  SIGUE LA GUÍA RÁPIDA (15 minutos)"
echo "   → Abre y sigue: GUIA_RAPIDA.md"
echo "   → Configura variables de entorno"
echo ""
echo "3️⃣  CONFIGURE GMAIL (10 minutos)"
echo "   → Ve a: https://myaccount.google.com/apppasswords"
echo "   → Genera contraseña de aplicación"
echo "   → Cópiala a tu .env en EMAIL_PASSWORD"
echo ""
echo "4️⃣  REINICIA EL SERVIDOR"
echo "   → Detén el servidor actual (Ctrl+C)"
echo "   → Ejecuta: pnpm start:dev"
echo ""
echo "5️⃣  PRUEBA EL SISTEMA"
echo "   → Crea una solicitud en el frontend"
echo "   → Espera ~1 minuto"
echo "   → Revisa email en genericosistem@gmail.com"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "📚 ARCHIVOS IMPORTANTES:"
echo "   • README_EMAIL.md              ← Índice principal"
echo "   • GUIA_RAPIDA.md               ← Configuración rápida"
echo "   • EMAIL_CONFIG.md              ← Documentación completa"
echo "   • .env.template                ← Template de variables"
echo "   • example_request.sql          ← Ejemplos de solicitudes"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "🆘 SI TIENES PROBLEMAS:"
echo "   → Consulta GUIA_RAPIDA.md sección '🆘 Solucionar Problemas'"
echo "   → Consulta EMAIL_CONFIG.md sección 'Troubleshooting'"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "✅ ¡Listo! Comienza con el paso 1"
echo ""
