services:
  - type: web
    name: asset-app-back
    runtime: node
    buildCommand: pnpm install --frozen-lockfile --prod=false && pnpm run build && pnpm run migrate:deploy
    startCommand: node dist/src/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: AUTH_TOKEN_EXPIRES_IN
        value: never
      - key: AUTH_IGNORE_TOKEN_EXPIRATION
        value: "true"
