services:
  - type: web
    name: asset-app-back
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: node dist/src/main.js
    envVars:
      - key: NODE_ENV
        value: production
