services:
  - type: web
    name: asset-app-back
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: node dist/src/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: AUTH_TOKEN_EXPIRES_IN
        value: never
      - key: AUTH_IGNORE_TOKEN_EXPIRATION
        value: "true"
